### ISSUE TITLE
AttributeError: unknown attribute: "days"

### ISSUE THREAD

**Issue by katerina009** [nickmaccarthy/python-datemath#10]
Hi, I have new version 1.4.7 of datemath and following code `dm("now-29d/d")` gives me an Attribute Error: `AttributeError: unknown attribute: "days"` Can you explain where the problem is? Thank you for your answer!

**Comment by nickmaccarthy** [comment]
hey @katerina009 , thanks for opening up an issue.  What version of python are you using?   Can you also show me the output of a `pip freeze` for whatever python you working in when this happens?  I'm wondering if you have a newer version of `arrow` that what is in requirements.txt for `1.4.7`.  Thank you!

**Comment by katerina009** [comment]
Yes, that's it. The last version of `arrow` is the problem. So I must write to `requirements.txt` exact version that works => `arrow==0.14`

**Comment by nickmaccarthy** [comment]
Great to hear, thats what I was figuring @katerina009 .  I went ahead and updated arrow and fixed this in the latest release of this module, `v1.4.9`.  Can you try that version and let me know if that fixes your issue?  Thank you!
