### ISSUE TITLE
Parser does not fail for some invalid expressions

### ISSUE THREAD

**Issue by oli-ver** [nickmaccarthy/python-datemath#15]
Currently the parser accepts the following datemath expressions (and just returns "now" in UTC):

```
+1ö
+1ä
+1ü
+1ß
+1,
+1.
```

Expected behavior: Error message "Not a valid timeunit: <character>"

I debugged the code to check why this is happening. It seems you are using the regular expression [a-zA-Z] to validate the character before beginning to calculate the date. Unfortunatley this leads to just leaving the while loop in `helper.py` without any further processing (or error handling):

![image](https://user-images.githubusercontent.com/965863/77116970-60e84d00-6a31-11ea-8522-a3aed88e04b2.png)
 
Kind regards

Oliver

**Comment by nickmaccarthy** [comment]
Thanks for finding this @oli-ver , this is something I have wanted to circle back on for a while, but never found the time.   I created PR https://github.com/nickmaccarthy/python-datemath/pull/17/files  .  If you get a chance, can you test that branch and let me know if you find any issues?

**Comment by oli-ver** [comment]
I tested it again. the validation works as expected now.
Thanks for fixing this so fast @nickmaccarthy.
