### ISSUE TITLE
Invalid datemath expression can lead to NoneType

### ISSUE THREAD

**Issue by kasium** [nickmaccarthy/python-datemath#25]
Hi,

when datemath gets an invalid argument, it can happen that `None `is returned instead of an exception. 
This is can lead to a weird NoneType if `datemath.datemath` is used instead of `datemath.parse`.

```python
import datemath

type(datemath.parse("2")) # --> None

datemath.datemath("2")   # AttributeError: 'NoneType' object has no attribute 'datetime'
```

I use version 1.5.2 (latest). It would be great if both cases could raise a parse exception.

Thanks,
Kai

**Comment by nickmaccarthy** [comment]
Thanks for bringing this up @iakum .  I believe I have fixed it.  Would you mind testing out branch issue_25 (PR should be linked in this issue) and see if that fixes your problem?  If it does, I'll create version 1.5.3 and get it out on pypi

**Comment by nickmaccarthy** [comment]
PR for reference: https://github.com/nickmaccarthy/python-datemath/pull/26

**Comment by kasium** [comment]
Works perfectly! Thanks

**Comment by nickmaccarthy** [comment]
perfect @iakum , i just release v1.5.4, let me know if that works for you and I will close this issue out.

**Comment by kasium** [comment]
Works perfectly. Thanks a lot
