### ISSUE TITLE
Datemath returns Arrow object instead of datetime

### ISSUE THREAD

**Issue by alecbrick** [nickmaccarthy/python-datemath#28]
https://github.com/nickmaccarthy/python-datemath/commit/831d8fbb17bc4f4affc4b8d32a47b3d8c22c63fa#diff-0c78ec8d26c114f347d763c31736b6259e763c9130e6c326b5aaba43a8cac224

Not sure if this was intentional (since the README _does_ say that an Arrow object is returned), but our code expects datetime objects here.

**Comment by nickmaccarthy** [comment]
@alecbrick , can you post a snippet of the code you are using where you expect it?

**Comment by nickmaccarthy** [comment]
@alecbrick , never-mind, I found the issue.  Its a bug, and I have fixed it.  I will pushing a new version shortly.

**Comment by nickmaccarthy** [comment]
@alecbrick v1.5.5 should be on pypi now which fixes this.  Let me know if you have any issues.
