### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by kasium** [nickmaccarthy/python-datemath#31]
Hi,

first thanks for creating this open source project.
Personally, I really love to use type hints and check them with mypy. So I wonder if it would be possible to add them to python-datemath as well?
Obviously, it makes sense to first drop old and out-of-maintenance python version like 2.7 and 3.5.

I'm happy to contribute and create a PR.

**Comment by nickmaccarthy** [comment]
@kasium would you mind elaborating a little further, maybe with a code example where they might beneficial?  Is there missing functionality or a bug(s) from this project without them?

**Comment by kasium** [comment]
So, w/o type hints, I just need to tell mypy to thread python-datemath as Any all the time. However, with type hints and mypy I could find issue beforehand caused by wrong types.
I guess it's a well known topic in python. Many projects already added typ hints like flask, sqlalchemy, click, arrow, etc.

**Comment by kasium** [comment]
Seems not be relevant for the maintainer --> closing
