### ISSUE TITLE
Arrow version is outdated

### ISSUE THREAD

**Issue by kasium** [nickmaccarthy/python-datemath#32]
Python-datemath has a hard dependency on arrow (0.5.2) which is quite outdated in comparison to the current version 1.1.0

**Comment by nickmaccarthy** [comment]
@kasium , i locked it at that version because arrow made some breaking changes once that broke this module.  Is there anything in particular in 1.1.0 that would enhance this if we were to upgrade?

**Comment by kasium** [comment]
@nickmaccarthy not in particular. I use arrow in a project and I would like to get the type hints they added in 1.0

**Comment by kasium** [comment]
Any update on this?

**Comment by kasium** [comment]
Seems not be relevant for the maintainer --> closing
