### ISSUE TITLE
Install fail with python3

### ISSUE THREAD

**Issue by gawel** [nickmaccarthy/python-datemath#4]
Hi. I get this error while intalling this package with pip (python 3.6):
```
Collecting python-datemath
  Downloading python-datemath-1.4.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b7eagia6/python-datemath/setup.py", line 16, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/home/gawel/bear/elder-hunter/lib/python3.6/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-b7eagia6/python-datemath/README.md'
```

I think you need a MANIFEST.in (or release a python3 .whl)

**Comment by gawel** [comment]
I see some progress (thanks)

Notice that you can release a universal wheel by adding this to your setup.cfg:

```
[bdist_wheel]
universal=1
```

This should be enough to release a py2/3 compatible wheel

**Comment by nickmaccarthy** [comment]
@gawel - thanks for pointing this out to me.  I made the fix and tested this against a few containers running various version of python3. I uploaded v1.4.6 to pypi - can you try to again with the latest version and let me know how things went?

**Comment by gawel** [comment]
Looks good. Even with ```pip install --no-use-wheel``` option. Thanks

**Comment by nickmaccarthy** [comment]
@gawel - thank you again!
