### ISSUE TITLE
Passed in timezone doesn't work for date string

### ISSUE THREAD

**Issue by clasnake** [nickmaccarthy/python-datemath#6]
Hi, passing in a timezone as the second argument works if the first argument is "now". However, it doesn't work if the first argument is a date string(e.g. 2017-09-22 10:20:00). The tzinfo returned is still tzutc() no matter which timezone I passed in.

**Comment by nickmaccarthy** [comment]
Hi @clasnake , thank you for pointing this out.  I believe I have this fixed this in v1.4.7.  Please install that version and let me know if that worked out for you either way if you wouldn't mind.

**Comment by clasnake** [comment]
@nickmaccarthy Thanks very much. I'll check it out early next week.

**Comment by clasnake** [comment]
Hey @nickmaccarthy, I just checked with the latest version and it works well. Thanks very much for the bug fix.

**Comment by nickmaccarthy** [comment]
Great the hear @clasnake , thanks again for bringing this one to my attention!
